site_name: Cocoa Gang Cinema
nav:
    - 'ğŸ  HlavnÃ­ strana': 'index.md'
    - 'ğŸ“— ZÃ¡kladnÃ­ informace':
        - 'ğŸ“… PlÃ¡novÃ¡nÃ­ (<1 min)': 'plan.md'
        - 'â“ Jak se ÃºÄastnit (<1 min)': 'ucast.md'
    - 'â¬‡ï¸ ZÃ¡kladnÃ­ instalace (5-10 min)': 'instalace-zaklad.md'
    - 'âš ï¸ PokroÄilejÅ¡Ã­ funkce':
        - 'ğŸŒ YouTube (10-15 min)': 'instalace-youtube.md'
theme: readthedocs